// Port of rust/crates/rails_compat/src/golden.rs
//
// Golden-vector tests against `vectors/rails_compat.json` (generated by the reference app with
// `reference-tools/rails_compat_vectors.rb`). The last test also writes what F# generates to
// `target/rails_compat_rust_output.json` (the name the verifier reads; the Rust crate writes the
// same file), which `reference-tools/rails_compat_verify_rust.rb` checks with Rails itself.
//
// Every test asserts how many vector cases it ran, so a case that is silently skipped fails.
module Campfire.RailsCompat.Tests.GoldenTests

open System
open System.IO
open System.Text
open System.Text.Json
open System.Threading.Tasks
open Xunit
open Campfire.RailsCompat
open Campfire.Tests

let private vectors = lazy (Repo.vector "rails_compat")

let private secrets = lazy (Secrets.create (nonNull (vectors.Value.RootElement.GetProperty("secret_key_base").GetString())))

/// Walks a dotted path through the vector, as `v("signed_cookies.generate")`.
let private v (path: string) : JsonElement =
    path.Split '.' |> Array.fold (fun (e: JsonElement) key -> e.GetProperty key) vectors.Value.RootElement

/// The array at `path`, and its length must be `expected`.
let private cases (path: string) (expected: int) : JsonElement[] =
    let all = (v path).EnumerateArray() |> Seq.toArray
    Assert.True((all.Length = expected), $"{path} has {all.Length} cases, expected {expected}")
    all

let private str (e: JsonElement) : string = nonNull (e.GetString())

let private optStr (e: JsonElement) : string option =
    if e.ValueKind = JsonValueKind.String then Some(str e) else None

let private time (e: JsonElement) : Timestamp = (Timestamps.tryParse (str e)).Value

let private optTime (e: JsonElement) : Timestamp option = optStr e |> Option.map (fun s -> (Timestamps.tryParse s).Value)

let private now () : Timestamp = time (v "now")

/// A vector value as a `Value`, key order and number kinds intact.
let private value (e: JsonElement) : Value = (Json.parse (Encoding.UTF8.GetBytes(e.GetRawText()))).Value

let private label (case: JsonElement) : string =
    match case.TryGetProperty "case" with
    | true, c -> $"case {c}"
    | _ -> "case"

/// `e?name` is the property `name` of a JSON object.
let private (?) (e: JsonElement) (name: string) : JsonElement = e.GetProperty name

let private eq (expected: 'a) (actual: 'a) (message: string) = Assert.True((expected = actual), message)

[<Fact>]
let ``key_generator`` () =
    for case in cases "key_generator" 6 do
        let key = secrets.Value.KeyGenerator.GenerateKey(str case?salt, case?length.GetInt32())
        Assert.True((Convert.ToHexStringLower key = str case?key_hex), $"salt {case?salt}")

[<Fact>]
let ``cookie_escaping`` () =
    for case in cases "cookie_escaping" 7 do
        match optStr case?raw with
        | Some raw -> Assert.True((Cookies.escape raw = str case?wire), $"escape {raw}")
        | None -> ()
        Assert.True((Cookies.unescape (str case?wire) = str case?parsed), $"unescape {case?wire}")

[<Fact>]
let ``cookie_escaping_is_rack_escape`` () =
    // `Rack::Utils.escape` of every character to U+00FF and ruby_compat's edge cases, from
    // `reference-tools/ruby_core.rb`.
    use rubyCore = Repo.vector "ruby_core"
    let strings = rubyCore.RootElement.GetProperty("strings").EnumerateArray() |> Seq.toArray
    Assert.Equal(427, strings.Length)
    for case in strings do
        let raw = str case?input
        Assert.True((Cookies.escape raw = str case?rack_escape), $"escape {raw}")

[<Fact>]
let ``signed_cookies_are_generated_byte_for_byte`` () =
    for case in cases "signed_cookies.generate" 10 do
        let raw = Cookies.sign secrets.Value (str case?name) (str case?value) (optTime case?expires_at)
        Assert.True((raw = str case?raw), $"value {case?value}")
        let setCookie = str case?set_cookie
        let first = setCookie.Split(';').[0]
        let wire = first.Substring(first.IndexOf '=' + 1)
        Assert.Equal(wire, Cookies.escape raw)

[<Fact>]
let ``permanent_cookies_expire_in_twenty_years`` () =
    let sessionToken = (cases "signed_cookies.generate" 10)[0]
    Assert.Equal(time sessionToken?expires_at, Cookies.permanentExpiresAt (now ()))

[<Fact>]
let ``signed_cookies_verify_like_rails`` () =
    for case in cases "signed_cookies.verify" 35 do
        let name, raw, at = str case?name, str case?raw, time case?now
        let verified = Cookies.verifySignedValue secrets.Value name raw at |> Option.defaultValue Value.Null
        eq (value case?expected) verified (label case)
        let asString = Cookies.verifySigned secrets.Value name raw at
        eq (optStr case?expected) asString (label case)

[<Fact>]
let ``encrypted_cookies_decrypt_like_rails`` () =
    for case in cases "encrypted_cookies.verify" 20 do
        let decrypted = Cookies.decrypt secrets.Value (str case?name) (str case?raw) (time case?now)
        eq (value case?expected) (decrypted |> Option.defaultValue Value.Null) (label case)

[<Fact>]
let ``encrypted_cookie_plaintext_matches_rails`` () =
    let encryptor = Cookies.encryptedCookieEncryptor secrets.Value
    for case in cases "encrypted_cookies.generate" 8 do
        let name = str case?name
        let plaintext = (MessageEncryptor.decrypt encryptor (str case?raw)).Value
        Assert.Equal(str case?plaintext, Encoding.UTF8.GetString plaintext)

        // Object keys keep their order here, so F#'s plaintext is byte-identical.
        let ours =
            Metadata.serializeWithMetadata
                Serializer.Null
                (Value.String(Json.encode (value case?value)))
                (Some $"cookie.{name}")
                (optTime case?expires_at)
        Assert.Equal(str case?plaintext, Encoding.UTF8.GetString ours)

        let raw = Cookies.encrypt secrets.Value name (value case?value) (optTime case?expires_at)
        eq (Some(value case?value)) (Cookies.decrypt secrets.Value name raw (now ())) (label case)

[<Fact>]
let ``rails_session_and_its_forms_are_accepted`` () =
    let session = v "session"
    Assert.Equal(302, session.GetProperty("post_with_form_token_status").GetInt32())
    Assert.Equal(422, session.GetProperty("post_with_bad_token_status").GetInt32())

    let hash = (Cookies.decrypt secrets.Value "_campfire_session" (str (session.GetProperty "session_cookie_raw")) (now ())).Value
    eq (value (session.GetProperty "session")) hash "session hash"

    let token = str (session.GetProperty "session_token_value")
    Assert.Equal(Some token, Cookies.verifySigned secrets.Value "session_token" (str (session.GetProperty "session_token_raw")) (now ()))
    let ours = Cookies.sign secrets.Value "session_token" token (Some(Cookies.permanentExpiresAt (now ())))
    Assert.Equal(str (session.GetProperty "session_token_raw"), ours)

[<Fact>]
let ``signed_ids`` () =
    for case in cases "signed_ids.generate" 14 do
        let model = str case?model
        let generated =
            SignedId.generate secrets.Value model (case?id.GetInt64()) (optStr case?purpose) (optTime case?expires_at)
        Assert.True((generated = str case?signed_id), $"{model} {case?id} {case?purpose}")
    for case in cases "signed_ids.verify" 31 do
        let id =
            SignedId.verify secrets.Value (str case?model) (str case?signed_id) (optStr case?purpose) (time case?now)
        let expected =
            match case?expected with
            | e when e.ValueKind = JsonValueKind.String -> Some(Int64.Parse(str e))
            | e when e.ValueKind = JsonValueKind.Number -> Some(e.GetInt64())
            | _ -> None
        eq expected id (label case)

[<Fact>]
let ``global_ids`` () =
    for case in cases "global_ids" 4 do
        let gid = (GlobalId.parse (str case?gid)).Value
        Assert.Equal(GlobalId.create (str case?model_name) (str case?id), gid)
        Assert.Equal(str case?gid, gid.ToString())
        Assert.Equal(str case?param, GlobalId.toParam gid)

[<Fact>]
let ``sgids`` () =
    Assert.Equal(str (v "sgids.app"), GlobalId.App)
    for case in cases "sgids.generate" 5 do
        let gid = (GlobalId.parse (str case?gid)).Value
        let data = str case?data
        let generated =
            if data.EndsWith "?expires_in" then
                Assert.Equal(str case?purpose, GlobalId.AttachablePurpose)
                GlobalId.attachableSgid secrets.Value gid
            else
                GlobalId.sgid secrets.Value gid (str case?purpose) (optTime case?expires_at)
        Assert.True((generated = str case?sgid), $"{data} for {case?purpose}")
    for case in cases "sgids.verify" 24 do
        let located = GlobalId.locateSigned secrets.Value (str case?sgid) (str case?purpose) (time case?now)
        eq (optStr case?expected |> Option.bind GlobalId.parse) located (label case)

[<Fact>]
let ``forged_sgids_are_rejected`` () =
    for model in [ "User"; "Rooms::Open"; "Account"; "Message"; "Rooms::Direct"; "Session" ] do
        let gid = GlobalId.create model "1"
        let forged =
            MessageVerifier.generate (GlobalId.verifier (Secrets.create "attacker")) (Value.String(gid.ToString())) (Some "attachable") None
        Assert.Equal(None, GlobalId.locateSigned secrets.Value forged "attachable" (now ()))

[<Fact>]
let ``turbo_stream_names`` () =
    for case in cases "turbo_stream_names.generate" 6 do
        let parts = [ for p in case?parts.EnumerateArray() -> str p ]
        Assert.Equal(str case?stream_name, String.concat ":" parts)
        Assert.Equal(str case?signed, Turbo.signedStreamName secrets.Value parts)
    for case in cases "turbo_stream_names.verify" 12 do
        let name = Turbo.verifiedStreamName secrets.Value (str case?signed)
        let expected =
            match case?expected with
            | e when e.ValueKind = JsonValueKind.Null -> None
            | e when e.ValueKind = JsonValueKind.String -> Some(str e)
            | e -> Some(e.GetRawText())
        eq expected name (label case)

[<Fact>]
let ``app_verifiers`` () =
    for case in cases "app_verifiers.generate" 8 do
        let verifier = RailsCompat.appVerifier secrets.Value (str case?name)
        let message = MessageVerifier.generateRaw verifier (str case?data_json) (optStr case?purpose) (optTime case?expires_at)
        Assert.True((message = str case?message), $"{case?name} {case?data_json}")
    for case in cases "app_verifiers.verify" 15 do
        let verifier = RailsCompat.appVerifier secrets.Value (str case?name)
        let data =
            MessageVerifier.verifyRaw verifier (str case?message) (optStr case?purpose) (time case?now)
            |> Result.toOption
        eq (optStr case?expected_json) data (label case)

[<Fact>]
let ``passwords`` () =
    Assert.Equal(Password.Cost, (v "passwords.cost").GetInt32())
    for case in cases "passwords.digests" 5 do
        Assert.StartsWith("$2a$12$", str case?digest)
    // Cost 12 takes a while per check, so run them side by side.
    let checks = cases "passwords.checks" 40
    let results =
        checks
        |> Array.map (fun case ->
            Task.Run(fun () ->
                let ok = Password.verify (str case?password) (str case?digest)
                (ok = (case?expected.ValueKind = JsonValueKind.True), $"{case?password} against {case?digest}")))
    for result in results do
        let (correct, message) = result.Result
        Assert.True(correct, message)
    Assert.True(Password.verify "secret123456" (str (v "passwords.seeded_user_digest")))
    let ours = (Password.digestWithCost "pässwörd ☃" Password.MinCost) |> Result.defaultWith (fun e -> failwith $"{e}")
    Assert.True(ours.StartsWith "$2a$04$" && Password.verify "pässwörd ☃" ours)
    Assert.True((Password.digestWithCost "secret" (Password.MinCost - 1) |> Result.isError))
    Assert.False(Password.verify "anything" "not a digest")

/// Writes F#-generated values for `reference-tools/rails_compat_verify_rust.rb`.
[<Fact>]
let ``write_rust_output_for_rails_to_verify`` () =
    let now = now ()
    let permanent = Cookies.permanentExpiresAt now
    let secrets = secrets.Value
    let str' (s: string) = Value.String s
    let optString (s: string option) = match s with Some s -> Value.String s | None -> Value.Null

    let signedCookies =
        [ for value in [ "token-from-rust"; "with space+plus/slash="; "<é&☃>"; "" ] do
              yield
                  Value.Object
                      [ "name", str' "session_token"
                        "value", str' value
                        "raw", str' (Cookies.sign secrets "session_token" value (Some permanent)) ]
          yield Value.Object [ "name", str' "other"; "value", str' "no expiry"; "raw", str' (Cookies.sign secrets "other" "no expiry" None) ] ]

    let encryptedCookies =
        [ for value in
              [ Value.Object [ "session_id", str' "rust-session-id"; "return_to_after_authenticating", str' "/rooms/1" ]
                Value.Object [ "return_to_after_authenticating", str' "http://campfire.test/rooms/1?a=1&b=<2>"; "n", Value.Int 1L ]
                str' "plain"
                Value.Array [ Value.Int 1L; Value.Null; str' "☃\u2028" ] ] ->
              Value.Object
                  [ "name", str' "_campfire_session"
                    "raw", str' (Cookies.encrypt secrets "_campfire_session" value (Some permanent))
                    "value", value ] ]

    let sessionToken = "RustMadeSessionToken1234"

    let fourHours = now.AddHours 4.0
    let signedIds =
        [ for (id, purpose, expiresAt) in
              [ 1L, Some "avatar", None
                2L, Some "transfer", Some fourHours
                12345L, None, None
                9_007_199_254_740_993L, Some "avatar", None ] ->
              Value.Object
                  [ "model", str' "User"
                    "id", Value.Int id
                    "purpose", optString purpose
                    "signed_id", str' (SignedId.generate secrets "User" id purpose expiresAt) ] ]

    let anHour = now.AddHours 1.0
    let sgids =
        [ Value.Object [ "sgid", str' (GlobalId.attachableSgid secrets (GlobalId.create "User" "1")); "purpose", str' "attachable"; "expected", str' "gid://campfire/User/1?expires_in" ]
          Value.Object [ "sgid", str' (GlobalId.attachableSgid secrets (GlobalId.create "User" "2")); "purpose", str' "attachable"; "expected", str' "gid://campfire/User/2?expires_in" ]
          Value.Object [ "sgid", str' (GlobalId.sgid secrets (GlobalId.create "User" "1") "attachable" (Some anHour)); "purpose", str' "attachable"; "expected", str' "gid://campfire/User/1" ]
          Value.Object [ "sgid", str' (GlobalId.sgid secrets (GlobalId.create "Rooms::Open" "1") "default" None); "purpose", str' "attachable"; "expected", Value.Null ] ]

    let room = GlobalId.toParam (GlobalId.create "Rooms::Open" "1")
    let user = GlobalId.toParam (GlobalId.create "User" "1")
    let turbo =
        [ for parts in [ [ room; "messages" ]; [ "rooms" ]; [ user; "rooms" ]; [ "unicode ☃ <&>" ] ] ->
              Value.Object [ "signed", str' (Turbo.signedStreamName secrets parts); "expected", str' (String.concat ":" parts) ] ]

    let digest password cost =
        match Password.digestWithCost password cost with
        | Ok digest -> digest
        | Error e -> failwith $"{e}"
    let passwords =
        [ for (password, cost) in [ "secret123456", Password.Cost; "pässwörd ☃", Password.MinCost; String('a', 80), Password.MinCost ] ->
              Value.Object [ "password", str' password; "digest", str' (digest password cost) ] ]

    let appVerifiers =
        [ for (dataJson, purpose, expiresAt) in
              [ "{\"key\":\"k1\",\"disposition\":\"inline; filename=\\\"a\\u0026b.png\\\"\",\"content_type\":\"image/png\",\"service_name\":\"local\"}", Some "blob_key", Some fourHours
                "42", Some "blob_id", None
                "{\"z\":1,\"a\":2}", Some "x", None ] ->
              Value.Object
                  [ "name", str' "ActiveStorage"
                    "data_json", str' dataJson
                    "purpose", optString purpose
                    "message", str' (MessageVerifier.generateRaw (RailsCompat.appVerifier secrets "ActiveStorage") dataJson purpose expiresAt) ] ]

    let output =
        Value.Object
            [ "app_verifiers", Value.Array appVerifiers
              "now", str' (str (v "now"))
              "signed_cookies", Value.Array signedCookies
              "encrypted_cookies", Value.Array encryptedCookies
              "session",
              Value.Object
                  [ "session_token", str' sessionToken
                    "session_token_cookie", str' (Cookies.sign secrets "session_token" sessionToken (Some permanent)) ]
              "signed_ids", Value.Array signedIds
              "sgids", Value.Array sgids
              "turbo_stream_names", Value.Array turbo
              "passwords", Value.Array passwords ]

    let path = Repo.path "target/rails_compat_rust_output.json"
    Directory.CreateDirectory(nonNull (Path.GetDirectoryName path)) |> ignore
    File.WriteAllText(path, Json.generate output + "\n", UTF8Encoding false)
