#!/usr/bin/env python3
"""Generates Html5ever/NamedEntities.fs and Unicode/WordRanges.fs.

  script/generate-tables.py ENTITIES_RS WORD_RANGES_TXT

ENTITIES_RS is web_atoms-0.1.3/entities.rs (the table markup5ever's tokenizer matches character
references against, from the WHATWG entity list); WORD_RANGES_TXT is "lo hi" hex lines, one per
range of code points the Rust regex crate's `\\w` matches (script/word-ranges.rs prints it).
"""
import re
import sys

entities_rs, word_txt = sys.argv[1], sys.argv[2]

entries = []
for line in open(entities_rs):
    m = re.match(r'\s*\("&([^"]+)", (\d+), (\d+)\),', line)
    if m:
        entries.append((m.group(1), int(m.group(2)), int(m.group(3))))
assert len(entries) == 2231, len(entries)

with open("Html5ever/NamedEntities.fs", "w") as out:
    out.write("// Generated by script/generate-tables.py from web_atoms 0.1.3's entities.rs: the named\n")
    out.write("// character references html5ever's tokenizer knows (2231, with and without the semicolon).\n")
    out.write("// Each entry is name:first[,second] with the code points in hex; entries are separated by spaces.\n")
    out.write("module internal Campfire.RichText.Html5ever.NamedEntities\n\n")
    out.write("let private blob =\n    \"\"\"\n")
    row = []
    for name, c1, c2 in entries:
        row.append(f"{name}:{c1:x}" + (f",{c2:x}" if c2 else ""))
        if len(row) == 8:
            out.write("    " + " ".join(row) + "\n")
            row = []
    if row:
        out.write("    " + " ".join(row) + "\n")
    out.write('    """\n\n')
    out.write("""/// `NAMED_ENTITIES`: every entity name without its `&`, and every proper prefix of one mapped to
/// (0, 0), so the tokenizer can tell a prefix of a name from a name that can't continue.
let table : System.Collections.Generic.Dictionary<string, struct (int * int)> =
    let table = System.Collections.Generic.Dictionary<string, struct (int * int)>(System.StringComparer.Ordinal)
    for entry in blob.Split([| ' '; '\\n' |], System.StringSplitOptions.RemoveEmptyEntries) do
        let colon = entry.IndexOf ':'
        let name = entry.Substring(0, colon)
        let codes = entry.Substring(colon + 1).Split ','
        let second = if codes.Length > 1 then System.Convert.ToInt32(codes[1], 16) else 0
        table[name] <- struct (System.Convert.ToInt32(codes[0], 16), second)
    for name in Seq.toArray table.Keys do
        for n in 1 .. name.Length - 1 do
            let prefix = name.Substring(0, n)
            if not (table.ContainsKey prefix) then table[prefix] <- struct (0, 0)
    table["" ] <- struct (0, 0)
    table
""")

ranges = [tuple(int(x, 16) for x in line.split()) for line in open(word_txt) if line.strip()]
with open("Unicode/WordRanges.fs", "w") as out:
    out.write("// Generated by script/generate-tables.py: the code points the Rust regex crate (1.13.1) matches\n")
    out.write("// with `\\w` (Unicode's Alphabetic, Mark, Decimal_Number, Connector_Punctuation and Join_Control).\n")
    out.write("module internal Campfire.RichText.Unicode.WordRanges\n\n")
    out.write(f"/// {len(ranges)} inclusive ranges, ascending, as lo0 hi0 lo1 hi1 ...\n")
    out.write("let ranges : int[] =\n    [|\n")
    flat = []
    for lo, hi in ranges:
        flat += [lo, hi]
    for i in range(0, len(flat), 8):
        out.write("        " + "; ".join(f"0x{v:x}" for v in flat[i:i+8]) + ";\n")
    out.write("    |]\n")
