// Port of rust/crates/campfire/src/controllers.rs
//
// The route table from `reference/config/routes.rb` (plus the framework routes `bin/rails routes`
// lists: Active Storage, Turbo Native navigation, Action Mailbox, `/up`), and a router that matches the
// way Rails' Journey does.
//
// Kestrel only sees `/cable` (a Falco endpoint) and, for everything else, `dispatch`, which picks the
// *first* route in table order whose verb and pattern match, exactly as Rails does. That matters:
// `GET /rooms/opens` is `rooms#show` with `id: "opens"` because `resources :rooms` is drawn before
// `namespace :rooms`. Patterns use Rails syntax: `:param` matches `[^/.?]+`, `*glob` matches lazily,
// and `(.:format)` is the optional format suffix (so `/rooms/1.json` sets `params[:format]`). Path
// params are percent-decoded and merged over query and body params, together with `controller` and
// `action`.
//
// The module is `RouteTable` because F# can't have a module `Controllers` beside the namespace of that
// name that holds the controllers themselves.
//
// ## Porting a controller
//
// Add `Controllers/Rooms.fs` (etc.) before this file in the project, write `show (c: Ctx)` actions that
// start with their before-action chain (see `Concerns`), and put `Rooms.show` in the matching rows in
// place of `unported "rooms#show"`, which answers 501 until its controller lands. Declared routes whose
// action Rails doesn't define (e.g. `first_runs#edit`) answer 404 like
// `AbstractController::ActionNotFound`: they map to `actionNotFound`. Never reorder, add or remove rows:
// the table must stay identical to `bin/rails routes` (checked by the tests against
// `vectors/campfire_routes.json`, generated by `reference-tools/campfire/routes.rb`).
namespace Campfire.App

open System
open System.Collections.Generic
open System.Text
open System.Text.RegularExpressions
open System.Threading.Tasks
open Microsoft.Extensions.Logging
open Campfire.RailsCompat
open Campfire.Kit
open Campfire.Routes
open Campfire.App.Controllers

type Route =
    { Verb: string
      /// The Rails path spec, e.g. `/rooms/:room_id/messages(.:format)`. Compiled into a regex; kept for
      /// the test that compares the table with `bin/rails routes`.
      Pattern: string
      /// `controller#action`, as `bin/rails routes` prints it.
      Endpoint: string
      Defaults: (string * string) list
      Action: ActionFn
      Regex: Regex
      Names: string[] }

    member this.Controller: string =
        match this.Endpoint.IndexOf '#' with
        | -1 -> this.Endpoint
        | i -> this.Endpoint.Substring(0, i)

    member this.ActionName: string =
        match this.Endpoint.IndexOf '#' with
        | -1 -> ""
        | i -> this.Endpoint.Substring(i + 1)

/// A declared route whose action the controller doesn't define (`AbstractController::ActionNotFound`).
module private Fallbacks =
    let actionNotFound (_: Ctx) : Task<Result<Response, Error>> = Task.FromResult(Error NotFound)

    /// A declared route whose controller doesn't exist, e.g. `resource :settings` under rooms: the
    /// reference answers 500 (the controller constant fails to load).
    let missingController (c: Ctx) : Task<Result<Response, Error>> =
        let endpoint =
            match c.Current<MatchedRoute>() with
            | ValueSome route -> route.Endpoint
            | ValueNone -> "?"
        Task.FromResult(Error(Internal(exn $"uninitialized constant for {endpoint}")))

    /// A route whose controller isn't ported yet (Phase 5's later units): 501, and a log line saying which.
    let unported (endpoint: string) : ActionFn =
        fun c ->
            c.Kit.Logger.LogError("route {Endpoint} is not ported yet", endpoint)
            Task.FromResult(Error(Status 501))

/// `Rails::HealthController`
module Health =
    let show (c: Ctx) : Task<Result<Response, Error>> =
        act {
            let! format = c.RespondTo [ Format.Html; Format.Json ]
            if format = Format.Json then
                let timestamp = DateTimeOffset.FromUnixTimeSeconds(c.Now().ToUnixTimeSeconds()).ToString("yyyy-MM-dd'T'HH:mm:ss'Z'")
                return c.Json(Status.Ok, Value.Object [ "status", Value.String "up"; "timestamp", Value.String timestamp ])
            else
                return c.Html """<!DOCTYPE html><html><body style="background-color: green"></body></html>"""
        }

/// `Turbo::Native::NavigationController` (turbo-rails)
module TurboNative =
    let recede (c: Ctx) : Task<Result<Response, Error>> = act { return c.Html "Going back…" }

    let resume (c: Ctx) : Task<Result<Response, Error>> = act { return c.Html "Staying put…" }

    let refresh (c: Ctx) : Task<Result<Response, Error>> = act { return c.Html "Refreshing…" }

/// Action Mailbox's ingress and conductor routes, which Campfire doesn't use.
module Mailbox =
    /// `ActionMailbox::BaseController#ensure_configured`: no ingress is configured.
    let ingressNotConfigured (c: Ctx) : Task<Result<Response, Error>> = act { return c.Head Status.NotFound }

    /// `Rails::Conductor::BaseController`: CSRF first, then `ensure_development_env`.
    let conductor (c: Ctx) : Task<Result<Response, Error>> =
        act {
            do! c.VerifyAuthenticityToken()
            return c.Head Status.Forbidden
        }

module RouteTable =
    let private actionNotFound = Fallbacks.actionNotFound
    let private missingController = Fallbacks.missingController
    let private unported = Fallbacks.unported

    /// A Journey path spec as an anchored regex, plus its parameter names in order.
    let compile (pattern: string) : Regex * string[] =
        let regex = StringBuilder("^")
        let names = ResizeArray<string>()
        let mutable i = 0
        while i < pattern.Length do
            let c = pattern[i]
            i <- i + 1
            match c with
            | '(' -> regex.Append "(?:" |> ignore
            | ')' -> regex.Append ")?" |> ignore
            | ':'
            | '*' ->
                let start = i
                while i < pattern.Length && (Char.IsAsciiLetterOrDigit pattern[i] || pattern[i] = '_') do
                    i <- i + 1
                regex.Append(if c = ':' then "([^/.?]+)" else "(.+?)") |> ignore
                names.Add(pattern.Substring(start, i - start))
            | other -> regex.Append(Regex.Escape(string other)) |> ignore
        regex.Append "\\z" |> ignore
        Regex(regex.ToString(), RegexOptions.CultureInvariant ||| RegexOptions.Compiled), names.ToArray()

    let private make (verb: string) (pattern: string) (endpoint: string) (action: ActionFn) : Route =
        let regex, names = compile pattern
        { Verb = verb
          Pattern = pattern
          Endpoint = endpoint
          Defaults = []
          Action = action
          Regex = regex
          Names = names }

    let private withDefaults (defaults: (string * string) list) (route: Route) : Route = { route with Defaults = defaults }

    let private get = make "GET"
    let private post = make "POST"
    let private patch = make "PATCH"
    let private put = make "PUT"
    let private delete = make "DELETE"

    /// `scope path: ":bot_key", defaults: { format: :json }`
    let private botDefaults = [ "format", "json" ]

    /// `scope defaults: { user_id: "me" }`
    let private meDefaults = [ "user_id", "me" ]

    /// Every route, in `config/routes.rb` order.
    let routes: Lazy<Route[]> =
        lazy
            [|
                get "/" "welcome#show" (Welcome.show)
                get "/first_run/new(.:format)" "first_runs#new" (actionNotFound)
                get "/first_run/edit(.:format)" "first_runs#edit" (actionNotFound)
                get "/first_run(.:format)" "first_runs#show" (FirstRuns.show)
                patch "/first_run(.:format)" "first_runs#update" (actionNotFound)
                put "/first_run(.:format)" "first_runs#update" (actionNotFound)
                delete "/first_run(.:format)" "first_runs#destroy" (actionNotFound)
                post "/first_run(.:format)" "first_runs#create" (FirstRuns.create)
                get "/session/transfers/:id(.:format)" "sessions/transfers#show" (SessionTransfers.show)
                patch "/session/transfers/:id(.:format)" "sessions/transfers#update" (SessionTransfers.update)
                put "/session/transfers/:id(.:format)" "sessions/transfers#update" (SessionTransfers.update)
                get "/session/new(.:format)" "sessions#new" (Sessions.``new``)
                get "/session/edit(.:format)" "sessions#edit" (actionNotFound)
                get "/session(.:format)" "sessions#show" (actionNotFound)
                patch "/session(.:format)" "sessions#update" (actionNotFound)
                put "/session(.:format)" "sessions#update" (actionNotFound)
                delete "/session(.:format)" "sessions#destroy" (Sessions.destroy)
                post "/session(.:format)" "sessions#create" (Sessions.create)
                get "/account/users(.:format)" "accounts/users#index" (AccountUsers.index)
                post "/account/users(.:format)" "accounts/users#create" (actionNotFound)
                get "/account/users/new(.:format)" "accounts/users#new" (actionNotFound)
                get "/account/users/:id/edit(.:format)" "accounts/users#edit" (actionNotFound)
                get "/account/users/:id(.:format)" "accounts/users#show" (actionNotFound)
                patch "/account/users/:id(.:format)" "accounts/users#update" (AccountUsers.update)
                put "/account/users/:id(.:format)" "accounts/users#update" (AccountUsers.update)
                delete "/account/users/:id(.:format)" "accounts/users#destroy" (AccountUsers.destroy)
                patch "/account/bots/:bot_id/key(.:format)" "accounts/bots/keys#update" (BotKeys.update)
                put "/account/bots/:bot_id/key(.:format)" "accounts/bots/keys#update" (BotKeys.update)
                get "/account/bots(.:format)" "accounts/bots#index" (Bots.index)
                post "/account/bots(.:format)" "accounts/bots#create" (Bots.create)
                get "/account/bots/new(.:format)" "accounts/bots#new" (Bots.``new``)
                get "/account/bots/:id/edit(.:format)" "accounts/bots#edit" (Bots.edit)
                get "/account/bots/:id(.:format)" "accounts/bots#show" (actionNotFound)
                patch "/account/bots/:id(.:format)" "accounts/bots#update" (Bots.update)
                put "/account/bots/:id(.:format)" "accounts/bots#update" (Bots.update)
                delete "/account/bots/:id(.:format)" "accounts/bots#destroy" (Bots.destroy)
                post "/account/join_code(.:format)" "accounts/join_codes#create" (JoinCodes.create)
                get "/account/logo(.:format)" "accounts/logos#show" (Logos.show)
                delete "/account/logo(.:format)" "accounts/logos#destroy" (Logos.destroy)
                get "/account/custom_styles/edit(.:format)" "accounts/custom_styles#edit" (CustomStyles.edit)
                patch "/account/custom_styles(.:format)" "accounts/custom_styles#update" (CustomStyles.update)
                put "/account/custom_styles(.:format)" "accounts/custom_styles#update" (CustomStyles.update)
                get "/account/new(.:format)" "accounts#new" (actionNotFound)
                get "/account/edit(.:format)" "accounts#edit" (AccountsController.edit)
                get "/account(.:format)" "accounts#show" (actionNotFound)
                patch "/account(.:format)" "accounts#update" (AccountsController.update)
                put "/account(.:format)" "accounts#update" (AccountsController.update)
                delete "/account(.:format)" "accounts#destroy" (actionNotFound)
                post "/account(.:format)" "accounts#create" (actionNotFound)
                get "/join/:join_code(.:format)" "users#new" (UsersController.``new``)
                post "/join/:join_code(.:format)" "users#create" (UsersController.create)
                get "/qr_code/:id(.:format)" "qr_code#show" (QrCode.show)
                get "/users/:user_id/avatar(.:format)" "users/avatars#show" (Avatars.show)
                delete "/users/:user_id/avatar(.:format)" "users/avatars#destroy" (Avatars.destroy)
                delete "/users/:user_id/ban(.:format)" "users/bans#destroy" (Bans.destroy)
                post "/users/:user_id/ban(.:format)" "users/bans#create" (Bans.create)
                get "/users/:user_id/sidebar(.:format)" "users/sidebars#show" (Sidebars.show) |> withDefaults meDefaults
                get "/users/:user_id/profile/new(.:format)" "users/profiles#new" (actionNotFound) |> withDefaults meDefaults
                get "/users/:user_id/profile/edit(.:format)" "users/profiles#edit" (actionNotFound) |> withDefaults meDefaults
                get "/users/:user_id/profile(.:format)" "users/profiles#show" (Profiles.show) |> withDefaults meDefaults
                patch "/users/:user_id/profile(.:format)" "users/profiles#update" (Profiles.update) |> withDefaults meDefaults
                put "/users/:user_id/profile(.:format)" "users/profiles#update" (Profiles.update) |> withDefaults meDefaults
                delete "/users/:user_id/profile(.:format)" "users/profiles#destroy" (actionNotFound) |> withDefaults meDefaults
                post "/users/:user_id/profile(.:format)" "users/profiles#create" (actionNotFound) |> withDefaults meDefaults
                post "/users/:user_id/push_subscriptions/:push_subscription_id/test_notifications(.:format)" "users/push_subscriptions/test_notifications#create" (TestNotifications.create) |> withDefaults meDefaults
                get "/users/:user_id/push_subscriptions(.:format)" "users/push_subscriptions#index" (PushSubscriptions.index) |> withDefaults meDefaults
                post "/users/:user_id/push_subscriptions(.:format)" "users/push_subscriptions#create" (PushSubscriptions.create) |> withDefaults meDefaults
                get "/users/:user_id/push_subscriptions/new(.:format)" "users/push_subscriptions#new" (actionNotFound) |> withDefaults meDefaults
                get "/users/:user_id/push_subscriptions/:id/edit(.:format)" "users/push_subscriptions#edit" (actionNotFound) |> withDefaults meDefaults
                get "/users/:user_id/push_subscriptions/:id(.:format)" "users/push_subscriptions#show" (actionNotFound) |> withDefaults meDefaults
                patch "/users/:user_id/push_subscriptions/:id(.:format)" "users/push_subscriptions#update" (actionNotFound) |> withDefaults meDefaults
                put "/users/:user_id/push_subscriptions/:id(.:format)" "users/push_subscriptions#update" (actionNotFound) |> withDefaults meDefaults
                delete "/users/:user_id/push_subscriptions/:id(.:format)" "users/push_subscriptions#destroy" (PushSubscriptions.destroy) |> withDefaults meDefaults
                get "/users/:id(.:format)" "users#show" (UsersController.show)
                get "/autocompletable/users(.:format)" "autocompletable/users#index" (AutocompletableUsers.index)
                get "/rooms/:room_id/messages(.:format)" "messages#index" (unported "messages#index")
                post "/rooms/:room_id/messages(.:format)" "messages#create" (unported "messages#create")
                get "/rooms/:room_id/messages/new(.:format)" "messages#new" (actionNotFound)
                get "/rooms/:room_id/messages/:id/edit(.:format)" "messages#edit" (unported "messages#edit")
                get "/rooms/:room_id/messages/:id(.:format)" "messages#show" (unported "messages#show")
                patch "/rooms/:room_id/messages/:id(.:format)" "messages#update" (unported "messages#update")
                put "/rooms/:room_id/messages/:id(.:format)" "messages#update" (unported "messages#update")
                delete "/rooms/:room_id/messages/:id(.:format)" "messages#destroy" (unported "messages#destroy")
                post "/rooms/:room_id/:bot_key/messages/:message_id/boosts(.:format)" "messages/boosts/by_bots#create" (unported "messages/boosts/by_bots#create") |> withDefaults botDefaults
                delete "/rooms/:room_id/:bot_key/messages/:message_id/boosts/:id(.:format)" "messages/boosts/by_bots#destroy" (unported "messages/boosts/by_bots#destroy") |> withDefaults botDefaults
                get "/rooms/:room_id/:bot_key/messages(.:format)" "messages/by_bots#index" (unported "messages/by_bots#index") |> withDefaults botDefaults
                post "/rooms/:room_id/:bot_key/messages(.:format)" "messages/by_bots#create" (unported "messages/by_bots#create") |> withDefaults botDefaults
                patch "/rooms/:room_id/:bot_key/messages/:id(.:format)" "messages/by_bots#update" (unported "messages/by_bots#update") |> withDefaults botDefaults
                put "/rooms/:room_id/:bot_key/messages/:id(.:format)" "messages/by_bots#update" (unported "messages/by_bots#update") |> withDefaults botDefaults
                delete "/rooms/:room_id/:bot_key/messages/:id(.:format)" "messages/by_bots#destroy" (unported "messages/by_bots#destroy") |> withDefaults botDefaults
                get "/rooms/:room_id/refresh(.:format)" "rooms/refreshes#show" (unported "rooms/refreshes#show")
                get "/rooms/:room_id/settings(.:format)" "rooms/settings#show" (missingController)
                get "/rooms/:room_id/involvement(.:format)" "rooms/involvements#show" (unported "rooms/involvements#show")
                patch "/rooms/:room_id/involvement(.:format)" "rooms/involvements#update" (unported "rooms/involvements#update")
                put "/rooms/:room_id/involvement(.:format)" "rooms/involvements#update" (unported "rooms/involvements#update")
                get "/rooms/:room_id/@:message_id(.:format)" "rooms#show" (unported "rooms#show")
                get "/rooms(.:format)" "rooms#index" (unported "rooms#index")
                post "/rooms(.:format)" "rooms#create" (actionNotFound)
                get "/rooms/new(.:format)" "rooms#new" (actionNotFound)
                get "/rooms/:id/edit(.:format)" "rooms#edit" (actionNotFound)
                get "/rooms/:id(.:format)" "rooms#show" (unported "rooms#show")
                patch "/rooms/:id(.:format)" "rooms#update" (actionNotFound)
                put "/rooms/:id(.:format)" "rooms#update" (actionNotFound)
                delete "/rooms/:id(.:format)" "rooms#destroy" (unported "rooms#destroy")
                get "/rooms/opens(.:format)" "rooms/opens#index" (unported "rooms/opens#index")
                post "/rooms/opens(.:format)" "rooms/opens#create" (unported "rooms/opens#create")
                get "/rooms/opens/new(.:format)" "rooms/opens#new" (unported "rooms/opens#new")
                get "/rooms/opens/:id/edit(.:format)" "rooms/opens#edit" (unported "rooms/opens#edit")
                get "/rooms/opens/:id(.:format)" "rooms/opens#show" (unported "rooms/opens#show")
                patch "/rooms/opens/:id(.:format)" "rooms/opens#update" (unported "rooms/opens#update")
                put "/rooms/opens/:id(.:format)" "rooms/opens#update" (unported "rooms/opens#update")
                delete "/rooms/opens/:id(.:format)" "rooms/opens#destroy" (unported "rooms/opens#destroy")
                get "/rooms/closeds(.:format)" "rooms/closeds#index" (unported "rooms/closeds#index")
                post "/rooms/closeds(.:format)" "rooms/closeds#create" (unported "rooms/closeds#create")
                get "/rooms/closeds/new(.:format)" "rooms/closeds#new" (unported "rooms/closeds#new")
                get "/rooms/closeds/:id/edit(.:format)" "rooms/closeds#edit" (unported "rooms/closeds#edit")
                get "/rooms/closeds/:id(.:format)" "rooms/closeds#show" (unported "rooms/closeds#show")
                patch "/rooms/closeds/:id(.:format)" "rooms/closeds#update" (unported "rooms/closeds#update")
                put "/rooms/closeds/:id(.:format)" "rooms/closeds#update" (unported "rooms/closeds#update")
                delete "/rooms/closeds/:id(.:format)" "rooms/closeds#destroy" (unported "rooms/closeds#destroy")
                get "/rooms/directs(.:format)" "rooms/directs#index" (unported "rooms/directs#index")
                post "/rooms/directs(.:format)" "rooms/directs#create" (unported "rooms/directs#create")
                get "/rooms/directs/new(.:format)" "rooms/directs#new" (unported "rooms/directs#new")
                get "/rooms/directs/:id/edit(.:format)" "rooms/directs#edit" (unported "rooms/directs#edit")
                get "/rooms/directs/:id(.:format)" "rooms/directs#show" (unported "rooms/directs#show")
                patch "/rooms/directs/:id(.:format)" "rooms/directs#update" (actionNotFound)
                put "/rooms/directs/:id(.:format)" "rooms/directs#update" (actionNotFound)
                delete "/rooms/directs/:id(.:format)" "rooms/directs#destroy" (unported "rooms/directs#destroy")
                get "/messages/:message_id/boosts(.:format)" "messages/boosts#index" (unported "messages/boosts#index")
                post "/messages/:message_id/boosts(.:format)" "messages/boosts#create" (unported "messages/boosts#create")
                get "/messages/:message_id/boosts/new(.:format)" "messages/boosts#new" (unported "messages/boosts#new")
                get "/messages/:message_id/boosts/:id/edit(.:format)" "messages/boosts#edit" (actionNotFound)
                get "/messages/:message_id/boosts/:id(.:format)" "messages/boosts#show" (actionNotFound)
                patch "/messages/:message_id/boosts/:id(.:format)" "messages/boosts#update" (actionNotFound)
                put "/messages/:message_id/boosts/:id(.:format)" "messages/boosts#update" (actionNotFound)
                delete "/messages/:message_id/boosts/:id(.:format)" "messages/boosts#destroy" (unported "messages/boosts#destroy")
                get "/messages(.:format)" "messages#index" (unported "messages#index")
                post "/messages(.:format)" "messages#create" (unported "messages#create")
                get "/messages/new(.:format)" "messages#new" (actionNotFound)
                get "/messages/:id/edit(.:format)" "messages#edit" (unported "messages#edit")
                get "/messages/:id(.:format)" "messages#show" (unported "messages#show")
                patch "/messages/:id(.:format)" "messages#update" (unported "messages#update")
                put "/messages/:id(.:format)" "messages#update" (unported "messages#update")
                delete "/messages/:id(.:format)" "messages#destroy" (unported "messages#destroy")
                delete "/searches/clear(.:format)" "searches#clear" (unported "searches#clear")
                get "/searches(.:format)" "searches#index" (unported "searches#index")
                post "/searches(.:format)" "searches#create" (unported "searches#create")
                post "/unfurl_link(.:format)" "unfurl_links#create" (UnfurlLinks.create)
                get "/webmanifest(.:format)" "pwa#manifest" (Pwa.manifest)
                get "/service-worker(.:format)" "pwa#service_worker" (Pwa.serviceWorker)
                get "/up(.:format)" "rails/health#show" (Health.show)
                get "/recede_historical_location(.:format)" "turbo/native/navigation#recede" (TurboNative.recede)
                get "/resume_historical_location(.:format)" "turbo/native/navigation#resume" (TurboNative.resume)
                get "/refresh_historical_location(.:format)" "turbo/native/navigation#refresh" (TurboNative.refresh)
                post "/rails/action_mailbox/postmark/inbound_emails(.:format)" "action_mailbox/ingresses/postmark/inbound_emails#create" (Mailbox.ingressNotConfigured)
                post "/rails/action_mailbox/relay/inbound_emails(.:format)" "action_mailbox/ingresses/relay/inbound_emails#create" (Mailbox.ingressNotConfigured)
                post "/rails/action_mailbox/sendgrid/inbound_emails(.:format)" "action_mailbox/ingresses/sendgrid/inbound_emails#create" (Mailbox.ingressNotConfigured)
                get "/rails/action_mailbox/mandrill/inbound_emails(.:format)" "action_mailbox/ingresses/mandrill/inbound_emails#health_check" (Mailbox.ingressNotConfigured)
                post "/rails/action_mailbox/mandrill/inbound_emails(.:format)" "action_mailbox/ingresses/mandrill/inbound_emails#create" (Mailbox.ingressNotConfigured)
                post "/rails/action_mailbox/mailgun/inbound_emails/mime(.:format)" "action_mailbox/ingresses/mailgun/inbound_emails#create" (Mailbox.ingressNotConfigured)
                get "/rails/conductor/action_mailbox/inbound_emails(.:format)" "rails/conductor/action_mailbox/inbound_emails#index" (Mailbox.conductor)
                post "/rails/conductor/action_mailbox/inbound_emails(.:format)" "rails/conductor/action_mailbox/inbound_emails#create" (Mailbox.conductor)
                get "/rails/conductor/action_mailbox/inbound_emails/new(.:format)" "rails/conductor/action_mailbox/inbound_emails#new" (Mailbox.conductor)
                get "/rails/conductor/action_mailbox/inbound_emails/:id(.:format)" "rails/conductor/action_mailbox/inbound_emails#show" (Mailbox.conductor)
                get "/rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)" "rails/conductor/action_mailbox/inbound_emails/sources#new" (Mailbox.conductor)
                post "/rails/conductor/action_mailbox/inbound_emails/sources(.:format)" "rails/conductor/action_mailbox/inbound_emails/sources#create" (Mailbox.conductor)
                post "/rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)" "rails/conductor/action_mailbox/reroutes#create" (Mailbox.conductor)
                post "/rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)" "rails/conductor/action_mailbox/incinerates#create" (Mailbox.conductor)
                get "/rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)" "active_storage/blobs/redirect#show" (ActiveStorage.blobsRedirect)
                get "/rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)" "active_storage/blobs/proxy#show" (ActiveStorage.blobsProxy)
                get "/rails/active_storage/blobs/:signed_id/*filename(.:format)" "active_storage/blobs/redirect#show" (ActiveStorage.blobsRedirect)
                get "/rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format)" "active_storage/representations/redirect#show" (ActiveStorage.representationsRedirect)
                get "/rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)" "active_storage/representations/proxy#show" (ActiveStorage.representationsProxy)
                get "/rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)" "active_storage/representations/redirect#show" (ActiveStorage.representationsRedirect)
                get "/rails/active_storage/disk/:encoded_key/*filename(.:format)" "active_storage/disk#show" (ActiveStorage.diskShow)
                put "/rails/active_storage/disk/:encoded_token(.:format)" "active_storage/disk#update" (ActiveStorage.diskUpdate)
                post "/rails/active_storage/direct_uploads(.:format)" "active_storage/direct_uploads#create" (ActiveStorage.directUploadsCreate)
            |]

    /// One verb's routes in table order, indexed by the first segment of their pattern: every pattern
    /// starts with a literal first segment (and `(.:format)` may follow it), so a path's first segment,
    /// cut at its first dot, names the only routes that can match it. (Rust asks a `RegexSet` for the
    /// first of a verb's patterns that match; .NET has none.)
    type private VerbRoutes =
        { Verb: string
          ByFirstSegment: Dictionary<string, Route[]> }

    let private firstSegmentOfPattern (pattern: string) : string =
        let rest = pattern.Substring 1
        let stop = rest.IndexOfAny [| '/'; '('; ':'; '*' |]
        if stop < 0 then rest else rest.Substring(0, stop)

    let private firstSegmentOfPath (path: string) : string =
        let rest = path.Substring 1
        let stop = rest.IndexOfAny [| '/'; '.' |]
        if stop < 0 then rest else rest.Substring(0, stop)

    let private byVerb: Lazy<Dictionary<string, VerbRoutes>> =
        lazy
            (let verbs = Dictionary<string, VerbRoutes>()
             for verb in routes.Value |> Array.map (fun route -> route.Verb) |> Array.distinct do
                 let ofVerb = routes.Value |> Array.filter (fun route -> route.Verb = verb)
                 let index = Dictionary<string, Route[]>(StringComparer.Ordinal)
                 for segment in ofVerb |> Array.map (fun route -> firstSegmentOfPattern route.Pattern) |> Array.distinct do
                     index[segment] <- ofVerb |> Array.filter (fun route -> firstSegmentOfPattern route.Pattern = segment)
                 verbs[verb] <- { Verb = verb; ByFirstSegment = index }
             verbs)

    /// `Journey::Router::Utils.normalize_path`: one leading slash, repeated slashes squeezed,
    /// trailing slashes dropped, percent-escapes upcased.
    let normalizePath (path: string) : string =
        let normalized = StringBuilder(path.Length + 1)
        for c in "/" + path do
            if not (c = '/' && normalized.Length > 0 && normalized[normalized.Length - 1] = '/') then normalized.Append c |> ignore
        while normalized.Length > 1 && normalized[normalized.Length - 1] = '/' do
            normalized.Length <- normalized.Length - 1
        let text = normalized.ToString()
        if text.Contains '%' then
            Regex.Replace(text, "%[a-fA-F0-9]{2}", (fun (m: Match) -> m.Value.ToUpperInvariant()), RegexOptions.CultureInvariant)
        else
            text

    /// `Journey::Router::Utils.unescape_uri`, then Rails' check that the parameter is valid UTF-8
    /// (`ActionController::BadRequest` otherwise).
    let private unescapeUri (value: string) : Result<string, Error> =
        let source = Encoding.UTF8.GetBytes value
        let bytes = ResizeArray<byte>(source.Length)
        let hex (b: byte) = if Char.IsAsciiHexDigit(char b) then Convert.ToInt32(string (char b), 16) else -1
        let mutable i = 0
        while i < source.Length do
            if source[i] = byte '%' && i + 2 < source.Length && hex source[i + 1] >= 0 && hex source[i + 2] >= 0 then
                bytes.Add(byte (hex source[i + 1] * 16 + hex source[i + 2]))
                i <- i + 3
            else
                bytes.Add source[i]
                i <- i + 1
        try
            Ok(UTF8Encoding(false, true).GetString(bytes.ToArray()))
        with :? DecoderFallbackException ->
            Error(BadRequest "Invalid path parameters: Invalid encoding")

    /// A matched route's path parameters: its defaults, then its captures (percent-decoded), then
    /// `controller` and `action`.
    let pathParams (route: Route) (m: Match) : Result<ParamMap, Error> =
        let pathParams = ParamMap()
        for (name, value) in route.Defaults do
            pathParams.Insert(name, Param.Str value)
        let mutable failure = None
        for i in 0 .. route.Names.Length - 1 do
            let group = m.Groups[i + 1]
            if failure.IsNone && group.Success then
                match unescapeUri group.Value with
                | Ok value -> pathParams.Insert(route.Names[i], Param.Str value)
                | Error e -> failure <- Some e
        match failure with
        | Some e -> Error e
        | None ->
            pathParams.Insert("controller", Param.Str route.Controller)
            pathParams.Insert("action", Param.Str route.ActionName)
            Ok pathParams

    /// The first route matching `method` and the normalized `path`, with its path parameters
    /// (defaults, then captures, then `controller`/`action`). HEAD requests match GET routes.
    let recognize (meth: string) (path: string) : Result<(Route * ParamMap) option, Error> =
        let verb = if meth = "HEAD" then "GET" else meth
        match byVerb.Value.TryGetValue verb with
        // Every pattern starts with a slash, so a path that doesn't can't match.
        | _ when path.Length = 0 || path[0] <> '/' -> Ok None
        | false, _ -> Ok None
        | true, candidates ->
            match candidates.ByFirstSegment.TryGetValue(firstSegmentOfPath path) with
            | false, _ -> Ok None
            | true, routes ->
                let mutable found = None
                let mutable i = 0
                while found.IsNone && i < routes.Length do
                    let m = routes[i].Regex.Match path
                    if m.Success then found <- Some(routes[i], m)
                    i <- i + 1
                match found with
                | None -> Ok None
                | Some(route, m) -> pathParams route m |> Result.map (fun pathParams -> Some(route, pathParams))

    /// `params` is body params, then query params, then path params (`request.parameters`).
    let private installPathParams (c: Ctx) (pathParams: ParamMap) : unit =
        c.Params.Merge pathParams
        c.PathParams.Merge pathParams

    /// The single entry point for everything but `/cable`: find the route, install its path params, run
    /// its action.
    let dispatch (c: Ctx) : Task<Result<Response, Error>> =
        match recognize c.Request.Method (normalizePath c.Request.Path) with
        | Error e -> Task.FromResult(Error e)
        | Ok None -> Task.FromResult(Error NotFound)
        | Ok(Some(route, pathParams)) ->
            installPathParams c pathParams
            c.SetCurrent { Endpoint = route.Endpoint }
            route.Action c
