# Runs inside the reference app (bin/rails runner, production, after assets:precompile) and
# exports everything campfire_assets needs from it:
#
#   vendor/<gem>/<path>     every gem-provided directory on the Propshaft load path, copied verbatim
#   vendor/LOAD_PATH        the load path, in Propshaft's order, as `reference:<dir>` / `vendor:<dir>`
#   vendor/MANIFEST.md      provenance: gem, version, source, path and sha256 of every vendored file
#   vendor/<gem>/<license>  each vendored gem's license file (all MIT), which its copies carry
#   $FIXTURES_DIR/*         golden outputs (tests/Campfire.Assets.Tests/reference): the precompiled manifest, sha256 of every compiled file,
#                           the rendered layout head tags, the Link header, public file headers
#
# Invoked by src/Campfire.Assets/script/revendor. ASSETS_DIR is the project directory to write
# vendor/ into and FIXTURES_DIR the directory for the golden outputs.
require "digest"
require "fileutils"
require "json"

out = Pathname.new(ENV.fetch("ASSETS_DIR"))
vendor = out.join("vendor")
fixtures = Pathname.new(ENV.fetch("FIXTURES_DIR"))
FileUtils.rm_rf(vendor)
FileUtils.mkdir_p([ vendor, fixtures ])

def files_under(dir)
  Dir.glob("**/*", File::FNM_DOTMATCH, base: dir).sort
    .reject { |f| File.basename(f).start_with?(".") }
    .select { |f| File.file?(File.join(dir, f)) }
end

def gem_for(path)
  Gem.loaded_specs.values.select { |spec| path.start_with?(spec.full_gem_path + "/") }.max_by { |spec| spec.full_gem_path.length }
end

def source_for(spec)
  source = spec.source
  if source.is_a?(Bundler::Source::Git)
    "#{source.uri}@#{source.revision}"
  else
    "rubygems"
  end
end

load_path_lines = []
provenance = []
vendored = {}

Rails.application.assets.load_path.paths.each do |path|
  path = path.to_s
  root = Rails.root.to_s + "/"

  if path.start_with?(root)
    load_path_lines << "reference:#{path.delete_prefix(root)}"
  else
    spec = gem_for(path) or raise "No gem owns asset path #{path}"
    vendored[spec.name] = spec
    rel = path.delete_prefix(spec.full_gem_path + "/")
    dest = vendor.join(spec.name, rel)
    load_path_lines << "vendor:#{spec.name}/#{rel}"

    files_under(path).each do |file|
      FileUtils.mkdir_p(dest.join(file).dirname)
      FileUtils.cp(File.join(path, file), dest.join(file))
      provenance << [ spec.name, spec.version.to_s, source_for(spec), "#{rel}/#{file}", Digest::SHA256.file(File.join(path, file)).hexdigest ]
    end
  end
end

vendored.each_value do |spec|
  licenses = Dir.glob("{MIT-LICENSE,LICENSE,LICENSE.*,LICENCE,COPYING}", base: spec.full_gem_path)
  raise "No license file in #{spec.name}" if licenses.empty?
  licenses.each { |license| FileUtils.cp(File.join(spec.full_gem_path, license), vendor.join(spec.name, license)) }
end

File.write(vendor.join("LOAD_PATH"), load_path_lines.join("\n") + "\n")

File.open(vendor.join("MANIFEST.md"), "w") do |md|
  md.puts "# Vendored assets"
  md.puts
  md.puts "Generated by `src/Campfire.Assets/script/revendor` from the reference app (`reference/`, #{ENV.fetch("REFERENCE_SHA", "unknown SHA")})."
  md.puts "Do not edit by hand. Every file is copied byte-for-byte from the gem that the reference's"
  md.puts "Gemfile.lock resolves, at the path Propshaft puts on its load path. `LOAD_PATH` lists the full"
  md.puts "load path in Propshaft's order (`reference:` entries are read straight from the submodule)."
  md.puts "Each gem's license file (all MIT) is copied beside its files, under `<gem>/`."
  md.puts
  md.puts "| Gem | Version | Source | Path | SHA-256 |"
  md.puts "|---|---|---|---|---|"
  provenance.each { |row| md.puts "| #{row.join(" | ")} |" }
end

# The precompiled manifest and a hash of every file assets:precompile wrote.
assets_dir = Rails.public_path.join("assets")
FileUtils.cp(assets_dir.join(".manifest.json"), fixtures.join("manifest.json"))
compiled = files_under(assets_dir.to_s).to_h { |f| [ f, Digest::SHA256.file(assets_dir.join(f)).hexdigest ] }
File.write(fixtures.join("compiled_sha256.json"), JSON.pretty_generate(compiled) + "\n")

# The layout head tags, rendered by the real helpers in a real controller request.
probe = Class.new(ActionController::Base) do
  def self.name = "ProbeController"
  def show
    render inline: %(<%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>\n<%= javascript_importmap_tags %>)
  end
end
_, headers, body = probe.action(:show).call(Rack::MockRequest.env_for("http://example.com/probe"))
html = +""
body.each { |chunk| html << chunk }
File.write(fixtures.join("stylesheet_link_tag_all.html"), html.split("\n<script type=\"importmap\"").first)
File.write(fixtures.join("javascript_importmap_tags.html"), "<script type=\"importmap\"" + html.split("\n<script type=\"importmap\"", 2).last)
File.write(fixtures.join("link_header.txt"), headers["link"].to_s)

# How ActionDispatch::Static answers for public files (last-modified is dropped: it's an mtime).
static = ActionDispatch::Static.new(->(_) { [ 404, { "x-cascade" => "pass" }, [] ] }, Rails.public_path.to_s,
  headers: Rails.application.config.public_file_server.headers)
requests = [
  [ "GET", "/robots.txt", {} ], [ "HEAD", "/robots.txt", {} ], [ "POST", "/robots.txt", {} ],
  [ "GET", "/404", {} ], [ "GET", "/404.html", {} ], [ "GET", "/500/", {} ], [ "GET", "/", {} ], [ "GET", "/nope", {} ],
  [ "GET", "/assets/", {} ], [ "GET", "/assets/.manifest.json", {} ], [ "GET", "/%72obots.txt", {} ],
  [ "GET", "/assets/../robots.txt", {} ]
]
compiled.keys.each do |file|
  requests << [ "GET", "/assets/#{file}", {} ]
end
first_sound = compiled.keys.find { |f| f.end_with?(".mp3") }
requests += [
  [ "GET", "/assets/#{first_sound}", { "HTTP_RANGE" => "bytes=0-9" } ],
  [ "GET", "/assets/#{first_sound}", { "HTTP_RANGE" => "bytes=-5" } ],
  [ "GET", "/assets/#{first_sound}", { "HTTP_RANGE" => "bytes=100-" } ],
  [ "GET", "/assets/#{first_sound}", { "HTTP_RANGE" => "bytes=99999999-" } ],
  [ "GET", "/assets/#{first_sound}", { "HTTP_RANGE" => "bytes=5-2" } ],
  [ "HEAD", "/assets/#{first_sound}", { "HTTP_RANGE" => "bytes=0-9" } ]
]
responses = requests.map do |method, path, env|
  status, response_headers, response_body = static.call(Rack::MockRequest.env_for(path, { method: method }.merge(env)))
  bytes = +"".b
  response_body.each { |chunk| bytes << chunk }
  response_body.close if response_body.respond_to?(:close)
  { method: method, path: path, env: env, status: status,
    headers: response_headers.to_h.except("last-modified").sort.to_h,
    body_sha256: Digest::SHA256.hexdigest(bytes) }
end
File.write(fixtures.join("static_responses.json"), JSON.pretty_generate(responses) + "\n")

puts "Exported #{provenance.size} vendored files and #{compiled.size} compiled assets to #{out}"
