<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="Html5ever/Types.fs" />
    <Compile Include="Html5ever/NamedEntities.fs" />
    <Compile Include="Html5ever/Tokenizer.fs" />
    <Compile Include="Html5ever/TreeBuilder.fs" />
    <Compile Include="Unicode/WordRanges.fs" />
    <Compile Include="Unicode/Chars.fs" />
    <Compile Include="Dom.fs" />
    <Compile Include="RubyExt.fs" />
    <Compile Include="Sanitizer.fs" />
    <Compile Include="RubyUri.fs" />
    <Compile Include="Error.fs" />
    <Compile Include="Attachables.fs" />
    <Compile Include="PlainText.fs" />
    <Compile Include="Content.fs" />
    <Compile Include="Filters.fs" />
    <Compile Include="Autolink.fs" />
    <Compile Include="ActionText.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Campfire.RailsCompat/Campfire.RailsCompat.fsproj" />
    <ProjectReference Include="../Campfire.Ruby/Campfire.Ruby.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Campfire.RichText.Tests" />
  </ItemGroup>
</Project>
