# Dumps the lookup tables the port copies verbatim from the reference gems. The argument picks
# which:
#
# * `marcel`: Marcel's extension, parent, and magic tables (after marcel/mime_type/definitions.rb
#   has extended them), which drive Active Storage's content type identification. They go to
#   crates/storage/src/tables.rs.
# * `approximations`: I18n's default transliteration approximations, which
#   ActionDispatch::Http::ContentDisposition uses for the ASCII `filename=` parameter. They go to
#   crates/rails_compat/src/content_disposition/approximations.rs.
#
# * `approximations-fsharp`: the same table as F#, for src/Campfire.RailsCompat/ContentDispositionApproximations.fs
#   (the F# port's counterpart of the Rust file above; added by the F# port, the Rust modes are unchanged).
#
# * `marcel-fsharp`: the same Marcel tables as F#, for src/Campfire.Storage/Tables.fs (the F# port's counterpart
#   of tables.rs; added by the F# port, the Rust modes are unchanged).
#
# Run it with the reference app's bundle and redirect to the table's file (`run.sh tables` writes
# both):
#
#   bundle exec ruby ../reference-tools/storage/dump_tables.rb marcel > ../crates/storage/src/tables.rs
require "marcel"
require "i18n"

def rust_bytes(string)
  "b\"" + string.b.bytes.map { |byte|
    if byte >= 0x20 && byte < 0x7f && byte != 0x22 && byte != 0x5c
      byte.chr
    else
      format("\\x%02x", byte)
    end
  }.join + "\""
end

def rust_str(string)
  string.inspect.gsub(/\\u\{?([0-9a-fA-F]+)\}?/) { "\\u{#{$1}}" }
end

def rust_matches(matches)
  "&[" + matches.map { |offset, value, children|
    range_start, range_end = offset.is_a?(Range) ? [ offset.begin, "Some(#{offset.end})" ] : [ offset, "None" ]
    children_code = children ? rust_matches(children) : "&[]"
    value_code = value ? "Some(#{rust_bytes(value)})" : "None"
    "Match { offset: #{range_start}, range_end: #{range_end}, value: #{value_code}, children: #{children_code} }"
  }.join(", ") + "]"
end

def header(sources)
  puts "// @generated by reference-tools/storage/dump_tables.rb from #{sources}."
  puts "// Do not edit by hand; regenerate against the reference image's bundle instead."
  puts "#![allow(clippy::all)]"
  puts
end

def dump_marcel
  header "marcel #{Marcel::VERSION}"
  puts "/// One entry of `Marcel::MAGIC`: `[offset, value, children]`, where offset may be a Range."
  puts "pub struct Match {"
  puts "    pub offset: usize,"
  puts "    pub range_end: Option<usize>,"
  puts "    pub value: Option<&'static [u8]>,"
  puts "    pub children: &'static [Match],"
  puts "}"
  puts

  puts "/// `Marcel::EXTENSIONS`: extension => type."
  puts "pub static EXTENSIONS: &[(&str, &str)] = &["
  Marcel::EXTENSIONS.sort.each { |ext, type| puts "    (#{rust_str(ext)}, #{rust_str(type)})," }
  puts "];"
  puts

  puts "/// `Marcel::TYPE_EXTS`: type => extensions, in table order (`extensions.first` matters)."
  puts "pub static TYPE_EXTS: &[(&str, &[&str])] = &["
  Marcel::TYPE_EXTS.sort.each { |type, exts| puts "    (#{rust_str(type)}, &[#{exts.map { rust_str(_1) }.join(", ")}])," }
  puts "];"
  puts

  puts "/// `Marcel::TYPE_PARENTS`: type => parent types."
  puts "pub static TYPE_PARENTS: &[(&str, &[&str])] = &["
  Marcel::TYPE_PARENTS.sort.each { |type, parents| puts "    (#{rust_str(type)}, &[#{parents.map { rust_str(_1) }.join(", ")}])," }
  puts "];"
  puts

  puts "/// `Marcel::MAGIC`, in lookup order (the first matching entry wins)."
  puts "pub static MAGIC: &[(&str, &[Match])] = &["
  Marcel::MAGIC.each { |type, matches| puts "    (#{rust_str(type)}, #{rust_matches(matches)})," }
  puts "];"
end

def dump_approximations
  header "i18n #{I18n::VERSION}"
  puts "/// `I18n::Backend::Transliterator::HashTransliterator::DEFAULT_APPROXIMATIONS`."
  puts "pub static APPROXIMATIONS: &[(char, &str)] = &["
  I18n::Backend::Transliterator::HashTransliterator::DEFAULT_APPROXIMATIONS.sort.each do |char, ascii|
    puts "    (#{char.inspect.tr('"', "'")}, #{rust_str(ascii)}),"
  end
  puts "];"
end

def dump_approximations_fsharp
  puts "// @generated by reference-tools/storage/dump_tables.rb from i18n #{I18n::VERSION}."
  puts "// Do not edit by hand; regenerate against the reference image's bundle instead."
  puts "/// `I18n::Backend::Transliterator::HashTransliterator::DEFAULT_APPROXIMATIONS`, by code point."
  puts "module internal Campfire.RailsCompat.ContentDispositionApproximations"
  puts
  puts "let approximations: (int * string)[] ="
  puts "    [|"
  I18n::Backend::Transliterator::HashTransliterator::DEFAULT_APPROXIMATIONS.sort.each do |char, ascii|
    abort "approximation for #{char.inspect} is not printable ASCII" unless ascii.match?(/\A[ -~]*\z/) && !ascii.match?(/["\\]/)
    puts format("        0x%04X, \"%s\" // %s", char.ord, ascii, char)
  end
  puts "    |]"
end

# An F# string literal: printable ASCII as it is, everything else as \uXXXX or \UXXXXXXXX.
def fsharp_str(string)
  "\"" + string.each_char.map { |char|
    code = char.ord
    if char == "\"" || char == "\\"
      "\\#{char}"
    elsif code >= 0x20 && code < 0x7f
      char
    elsif code <= 0xffff
      format("\\u%04X", code)
    else
      format("\\U%08X", code)
    end
  }.join + "\""
end

# Marcel's magic values are binary. A byte string literal is allowed to hold printable ASCII only
# (the compiler warns about anything past 127), so other values are written as byte arrays.
def fsharp_bytes(string)
  bytes = string.b.bytes
  if bytes.all? { |byte| byte >= 0x20 && byte < 0x7f }
    "\"" + bytes.map { |byte| byte == 0x22 || byte == 0x5c ? "\\#{byte.chr}" : byte.chr }.join + "\"B"
  else
    "[|" + bytes.map { |byte| format("0x%02Xuy", byte) }.join("; ") + "|]"
  end
end

def fsharp_matches(matches)
  return "[||]" if matches.empty?
  "[|" + matches.map { |offset, value, children|
    value_code = value ? "Some #{fsharp_bytes(value)}" : "None"
    children_code = children ? fsharp_matches(children) : "[||]"
    if offset.is_a?(Range)
      "r #{offset.begin} #{offset.end} (#{value_code}) #{children_code}"
    else
      "m #{offset} (#{value_code}) #{children_code}"
    end
  }.join("; ") + "|]"
end

def dump_marcel_fsharp
  puts "// @generated by reference-tools/storage/dump_tables.rb from marcel #{Marcel::VERSION}."
  puts "// Do not edit by hand; regenerate against the reference image's bundle instead."
  puts "module internal Campfire.Storage.Tables"
  puts
  puts "/// One entry of `Marcel::MAGIC`: `[offset, value, children]`, where offset may be a Range."
  puts "[<NoComparison; ReferenceEquality>]"
  puts "type Match ="
  puts "    { Offset: int"
  puts "      RangeEnd: int option"
  puts "      Value: byte[] option"
  puts "      Children: Match[] }"
  puts
  puts "let private m (offset: int) (value: byte[] option) (children: Match[]) : Match ="
  puts "    { Offset = offset; RangeEnd = None; Value = value; Children = children }"
  puts
  puts "let private r (offset: int) (rangeEnd: int) (value: byte[] option) (children: Match[]) : Match ="
  puts "    { Offset = offset; RangeEnd = Some rangeEnd; Value = value; Children = children }"
  puts

  puts "/// `Marcel::EXTENSIONS`: extension => type."
  puts "let extensions: (string * string)[] ="
  puts "    [|"
  Marcel::EXTENSIONS.sort.each { |ext, type| puts "        #{fsharp_str(ext)}, #{fsharp_str(type)}" }
  puts "    |]"
  puts

  puts "/// `Marcel::TYPE_EXTS`: type => extensions, in table order (`extensions.first` matters)."
  puts "let typeExts: (string * string[])[] ="
  puts "    [|"
  Marcel::TYPE_EXTS.sort.each { |type, exts| puts "        #{fsharp_str(type)}, [|#{exts.map { fsharp_str(_1) }.join("; ")}|]" }
  puts "    |]"
  puts

  puts "/// `Marcel::TYPE_PARENTS`: type => parent types."
  puts "let typeParents: (string * string[])[] ="
  puts "    [|"
  Marcel::TYPE_PARENTS.sort.each { |type, parents| puts "        #{fsharp_str(type)}, [|#{parents.map { fsharp_str(_1) }.join("; ")}|]" }
  puts "    |]"
  puts

  puts "/// `Marcel::MAGIC`, in lookup order (the first matching entry wins)."
  puts "let magic: (string * Match[])[] ="
  puts "    [|"
  Marcel::MAGIC.each { |type, matches| puts "        #{fsharp_str(type)}, #{fsharp_matches(matches)}" }
  puts "    |]"
end

case ARGV.first
when "marcel" then dump_marcel
when "approximations" then dump_approximations
when "approximations-fsharp" then dump_approximations_fsharp
when "marcel-fsharp" then dump_marcel_fsharp
else abort "usage: dump_tables.rb marcel|approximations|approximations-fsharp|marcel-fsharp"
end
