<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/Repo.fs" Link="Repo.fs" />
    <Compile Include="HelpersTests.fs" />
    <Compile Include="ServeTests.fs" />
    <Compile Include="ReferenceTests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Campfire.Assets/Campfire.Assets.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
